name: setup-go
description: Sets up a Go build environment.

inputs:
  version:
    description: Go version
    default: 1.18.7

runs:
  using: composite
  steps:
    - uses: actions/setup-go@v3
      with:
        go-version: '${{ inputs.version }}'

    - shell: bash
      run: go version
