name: setup-go
description: Sets up a Go build environment.

inputs:
  # TODO(ver): CI should validate at this version matches that in the Dockerfile
  version:
    description: Go version
    default: 1.22

runs:
  using: composite
  steps:
    - uses: actions/setup-go@v5
      with:
        go-version: '${{ inputs.version }}'
