version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/.devcontainer"
    schedule:
      interval: daily
      time: "05:00"
      timezone: "UTC"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "UTC"
