name: setup-rust
description: Sets up a Rust build environment.

inputs:
  version:
    description: Container image version
    default: 1.64.0

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        export DEBIAN_FRONTEND=noninteractive
        sudo apt-get update
        sudo apt-get install -y clang cmake libssl-dev llvm pkg-config

    - shell: bash
      run: |
        rm -rf "$HOME/.cargo"
        curl --proto '=https' --tlsv1.3 -sSfLv 'https://sh.rustup.rs' | sh -s -- -y --default-toolchain '${{ inputs.version }}'
        source ~/.cargo/env
        (
          echo PATH="$PATH"
          echo CARGO_INCREMENTAL=0
          echo CARGO_NET_RETRY=10
          echo RUST_BACKTRACE=short
          echo RUSTUP_MAX_RETRIES=10
        ) >> "$GITHUB_ENV"

    - shell: bash
      run: rustup component add clippy rustfmt

    - shell: bash
      run: |
        set -xeuo pipefail
        cargo version
