name: setup-tools
description: Unpacks dev tools.

inputs:
  # TODO(ver): CI should validate at this version matches the most recent release tag
  version:
    description: Container image version
    default: v37

runs:
  using: composite
  steps:
    - uses: docker/setup-buildx-action@v2

    - name: Extract tools
      shell: bash
      run: |
        set -xeuo pipefail

        build=$(mktemp -d '${{ runner.temp }}/build.XXXX')
        echo 'FROM ghcr.io/linkerd/dev:${{ inputs.version }}-tools' > "$build"/Dockerfile

        tools=$(mktemp -d '${{ runner.temp }}/tools.XXXX')
        docker buildx build "$build" --output="type=local,dest=$tools/"
        (
          echo K3S_IMAGES_JSON="$tools/etc/k3s-images.json"
          echo PATH="$tools/bin:$PATH"
        ) >> "$GITHUB_ENV"

    - shell: bash
      run: sudo apt-get update && sudo apt-get install -y --no-install-recommends jo jq
