name: setup-tools
description: Unpacks dev tools.

inputs:
  # TODO(ver): CI should validate at this version matches the most recent release tag
  version:
    description: Container image version
    default: v48

runs:
  using: composite
  steps:
    - name: "Hack mandb"
      shell: bash
      run: |
        sudo dpkg-divert --local --rename --add /usr/bin/mandb
        sudo ln -sf /bin/true /usr/bin/mandb

    - shell: bash
      run: sudo apt-get update && sudo apt-get install -y --no-install-recommends jo umoci

    - name: Extract tools
      shell: bash
      run: |
        set -xeuo pipefail

        oci_dir=$(mktemp -d '${{ runner.temp }}/oci.XXXX')
        bundle_dir=$(mktemp -d '${{ runner.temp }}/bundle.XXXX')

        skopeo copy \
          "docker://ghcr.io/linkerd/dev:${{ inputs.version }}-tools" \
          "oci:$oci_dir:tools"

        umoci unpack --rootless --image "$oci_dir:tools" "$bundle_dir"

        tools="$bundle_dir/rootfs"
        (
          echo K3S_IMAGES_JSON="$tools/etc/k3s-images.json"
          echo PATH="$tools/bin:$PATH"
        ) >> "$GITHUB_ENV"
