name: Devcontainer

on:
  pull_request:
    paths:
      - .devcontainer/**
      - .github/workflows/devcontainer.yml
      - Dockerfile
      - justfile

permissions:
  contents: read

jobs:
  dev-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - uses: ./actions/setup-tools
      - run: just build

  dev-shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - uses: ./actions/setup-tools
      - run: just-sh

  dev-pull:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - uses: ./actions/setup-tools
      - run: just-dev pull-dev-image

  markdownlint:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - uses: DavidAnson/markdownlint-cli2-action@ded1f9488f68a970bc66ea5619e13e9b52e601cd
        with:
          globs: |
            **/*.md
            !repos/**
